name: Build 3DS Homebrew

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Install tools
        run: |
          dkp-pacman -Sy
          dkp-pacman -S --noconfirm 3ds-dev libctru

      - name: Build 3DSX
        run: make

      - name: Convert to CIA
        run: |
          3dsxtool *.3dsx output.elf
          makerom -f cia -o game.cia -elf output.elf

      - name: Upload CIA
        uses: actions/upload-artifact@v4
        with:
          name: cia
          path: "*.cia"
