name: Build 3DS Homebrew

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install 3DS libs
        run: |
          dkp-pacman -Sy
          dkp-pacman -S --noconfirm 3ds-dev libctru

      - name: Build
        run: |
          make clean || true
          make

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: 3ds-build
          path: "*.3dsx"
